site_name: DrugSLM Documentation
site_author: Vinícius de Lima Gonçalves

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - navigation.indexes
    - navigation.top

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format or set "yaml.customTags": ["!python/name:*"]

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Project Architecture:
      - architecture/index.md
      - Visual Standards: architecture/standards.md
      - Data Roadmap:
          - architecture/roadmap/index.md
          - Phase 1 Detailment: architecture/roadmap/phase1.md
      - Infrastructure: architecture/infrastructure.md
  - Library Design:
      - design/index.md
      - Sources:
          - ANVISA:
              - Categories: design/sources/anvisa/categories.md
  - API Reference:
      - reference/index.md
      - Sources:
          - reference/sources/index.md
          - ANVISA:
              - reference/sources/anvisa/index.md
              - Categories: reference/sources/anvisa/categories.md
      # - Canonical: []
      # - Features: []
      # - Models: []
      # - Database: []
      # - Analysis: []
      - Config:
          - Tree: reference/config/tree.md
      - Utils:
          - Selenium: reference/utils/selenium.md
