site_name: DrugSLM Documentation
site_author: Vinícius de Lima Gonçalves

site_url: ""
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - navigation.indexes
    - navigation.top

extra_css:
  - assets/stylesheets/mermaid.css

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format or set "yaml.customTags": ["!python/name:*"]

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture:
      - architecture/index.md
      - Standards: architecture/standards.md
      - Roadmap:
          - architecture/roadmap/index.md
          - Phase 1 Detailment: architecture/roadmap/phase1.md
      - Infrastructure: architecture/infrastructure.md
  - Design Reference:
      - design/index.md
      - Datasets:
          - Sources:
              - ANVISA:
                  - Categories: design/datasets/sources/anvisa/categories.md
  - API Reference:
      - reference/index.md
      - Datasets:
          - reference/datasets/index.md
          - Sources:
              - reference/datasets/sources/index.md
              - ANVISA:
                  - reference/datasets/sources/anvisa/index.md
                  - Categories: reference/datasets/sources/anvisa/categories.md
          - Transform: []
          - Features: []
          - Loaders: []

      - Models:
          - Definitions: []
          - Adapters: []
          - RAG: []

      - Training:
          - Loops: []
          - Objectives: []
          - RLHF: []

      - Evaluation:
          - Metrics: []
          - Benchmarks: []

      - Interface:
          - Chat: []
          - Telemetry: []
          - Deploy: []

      - Experiments:
          - Tracking: []
          - Visualization: []
          - Storytelling: []

      - Core:
        - Config:
            - Tree: reference/config/tree.md
        - Database: []
        - Utils:
            - Selenium: reference/utils/selenium.md
