site_name: DrugsLM Documentation
site_author: Vinícius de Lima Gonçalves

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - navigation.indexes

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]
          options:
            show_source: true
            show_root_heading: true
  - kroki:
      ServerURL: http://kroki.lilith.hell/
      FencePrefix: ""
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Docs:
      - reference/reference.md
      - scraper:
          - anvisa:
              - reference/scraper/anvisa/anvisa.md
              - build_index: reference/scraper/anvisa/build_index.md
              - pipelines: reference/scraper/anvisa/pipelines.md
              - config: reference/scraper/anvisa/config.md
          - selenium: reference/scraper/selenium.md
#
# !TODO: not working because docker inotify?
# watch:
#   - ../drugslm
#   - .
